services:
  proxy-haproxy:
    image: haproxy:latest
    container_name: proxy-haproxy
    ports:
      - "1443:443"
    volumes:
      - ./certs/:/certs/:ro
      - ./proxy-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs/ca/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./certs/ca/dev-ca.crt:/usr/local/share/ca-certificates/dev-ca.crt:ro
    networks:
      - net

  api1:
    container_name: api1
    environment:
      - Kestrel__Endpoints__Https__Url=https://*:443
      - Kestrel__Endpoints__Https__Certificate__Path=/certs/localhost.crt
      - Kestrel__Endpoints__Https__Certificate__KeyPath=/certs/localhost.key
    build:
      context: Api1
      dockerfile: Dockerfile
    ports:
      - 3443:443
    networks:
      - net
    volumes:
      - ./certs/ca/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./certs/ca/dev-ca.crt:/usr/local/share/ca-certificates/dev-ca.crt:ro
      - ./certs:/certs:ro

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=secret
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_SPI_X509CERT_LOOKUP_PROVIDER=haproxy
      - KC_SPI_X509CERT_LOOKUP_HAPROXY_SSL_CLIENT_CERT=SSL_CLIENT_CERT
      - KC_PROXY=reencrypt
      # - KC_PROXY=edge
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME=localhost
      # - KC_HTTP_ENABLED=true
      # - KC_HTTPS_CLIENT_AUTH=request
      - KC_HTTPS_CERTIFICATE_FILE=/certs/localhost.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/certs/localhost.key
      - KC_FEATURES=token-exchange,admin-fine-grained-authz
      - KC_LOG_CONSOLE_COLOR=true
      - KC_LOG_LEVEL=debug,org.hibernate:info
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=true
      - QUARKUS_HTTP_ACCESS_LOG_PATTERN="%r\n%{ALL_REQUEST_HEADERS}"
    volumes:
      - ./certs/ca/root-ca.crt:/etc/pki/ca-trust/source/anchors/root-ca.crt:ro
      - ./keycloak-entrypoint.sh:/keycloak-entrypoint.sh:ro
      - ./keycloak/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./certs:/certs:ro
    entrypoint: ["/keycloak-entrypoint.sh"]
    ports:
      - "8443:443"
    command: ["start"]
    networks:
      - net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net

  test-root-ca:
    image: nginx:latest
    container_name: test-root-ca
    volumes:
      - ./test-root-ca/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/ca/root-ca.crt:/etc/pki/ca-trust/source/anchors/root-ca.crt:ro
      - ./certs:/certs:ro
    ports:
      - "1080:80"
    networks:
      - net

networks:
  net:
volumes:
  postgres-data:
