services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "1443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/ca/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-docker-entrypoint.sh:/nginx-docker-entrypoint.sh:ro
    entrypoint: ["/nginx-docker-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - backend
      - api1
      - keycloak
    networks:
      - net

  api1:
    container_name: api1
    environment:
      - Kestrel__Endpoints__Https__Url=https://*:443
      - Kestrel__Endpoints__Https__Certificate__Path=/certs/localhost.crt
      - Kestrel__Endpoints__Https__Certificate__KeyPath=/certs/localhost.key
    build:
      context: Api1
      dockerfile: Dockerfile
    ports:
      - 3443:443
    networks:
      - net
    volumes:
      - ./certs/ca/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./certs/ca/dev-ca.crt:/usr/local/share/ca-certificates/dev-ca.crt:ro
      - ./certs:/certs:ro

  backend:
    image: nginx:latest
    container_name: backend
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/ca/root-ca.crt:/usr/local/share/ca-certificates/root-ca.crt:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-docker-entrypoint.sh:/nginx-docker-entrypoint.sh:ro
    entrypoint: ["/nginx-docker-entrypoint.sh"]
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - "2443:443"
    networks:
      - net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_SPI_X509CERT_LOOKUP_PROVIDER=nginx
      - KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT-CERT=X-SSL-CLIENT-CERT
      - KC_PROXY_HEADERS=xforwarded
    volumes:
      - ./certs/ca/root-ca.crt:/etc/pki/ca-trust/source/anchors/root-ca.crt:ro
      - ./keycloak-entrypoint.sh:/keycloak-entrypoint.sh:ro
    entrypoint: ["/keycloak-entrypoint.sh"]
    ports:
      - "8080:8080"
    command: ["start-dev"]
    networks:
      - net

  test-root-ca:
    image: nginx:latest
    container_name: test-root-ca
    volumes:
      - ./test-root-ca/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/ca/root-ca.crt:/etc/pki/ca-trust/source/anchors/root-ca.crt:ro
      - ./certs:/certs:ro
    ports:
      - "1080:80"
    networks:
      - net

networks:
  net:
